/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.clase;
import javax.swing.JOptionPane;

/**
 *
 * @author Camilo_Escobar
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    int lon;
    String contra;

    public Principal() {
        initComponents();
        cmdGuardarContra.setEnabled(true);
        cmdCambiarContra.setEnabled(false);
        cmdSeguridad.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdLimpiar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPassContra = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        cmdGuardarContra = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdSeguridad = new javax.swing.JButton();
        cmdCambiarContra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRes = new javax.swing.JTextArea();
        cmdLimpiar = new javax.swing.JButton();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel1.setText("Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        txtPassContra.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jPanel1.add(txtPassContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 200, 30));

        jLabel2.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, 30));

        cmdGuardarContra.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        cmdGuardarContra.setText("Guardar Contraseña");
        cmdGuardarContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarContraActionPerformed(evt);
            }
        });
        jPanel1.add(cmdGuardarContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        cmdMostrar.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 160, -1));

        cmdSeguridad.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        cmdSeguridad.setText("Tipo de seguridad");
        cmdSeguridad.setToolTipText("Saber si la contraseña es fuerte o no\n");
        cmdSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSeguridadActionPerformed(evt);
            }
        });
        jPanel1.add(cmdSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 160, -1));

        cmdCambiarContra.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        cmdCambiarContra.setText("Cambiar contraseña");
        cmdCambiarContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCambiarContraActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCambiarContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 160, -1));

        txtRes.setEditable(false);
        txtRes.setColumns(20);
        txtRes.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txtRes.setRows(5);
        jScrollPane1.setViewportView(txtRes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 370, 150));

        cmdLimpiar.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 420));

        setSize(new java.awt.Dimension(708, 490));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdGuardarContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarContraActionPerformed
        // TODO add your handling code here:
        clase p;
        if (txtPassContra.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite Contraseña por favor", "error", JOptionPane.ERROR_MESSAGE);
            txtPassContra.requestFocusInWindow();
        } else {
            contra = txtPassContra.getText();
            lon = contra.length();
            p = new clase(lon, contra);
            JOptionPane.showMessageDialog(this, "Contraseña guardada corractamente");
            cmdCambiarContra.setEnabled(true);
            cmdSeguridad.setEnabled(true);
            cmdMostrar.setEnabled(true);
            cmdLimpiar.setEnabled(true);
            cmdGuardarContra.setEnabled(false);
            txtPassContra.setEditable(false);
        }
    }//GEN-LAST:event_cmdGuardarContraActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed

        clase p;

        clase c;

        contra = txtPassContra.getText();
        lon = contra.length();
        p = new clase(lon, contra);
        c = p.mostrar();
        txtRes.setText("Su contraseña actual es: " + c.getContra() + "\n"
                + " longitud de su contraseña es: " + c.getLongitud());
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSeguridadActionPerformed
        // TODO add your handling code here:

        String c;
        clase p;
        contra = txtPassContra.getText();
        lon = contra.length();
        p = new clase(lon, contra);
        c = p.fuerte();
        txtRes.setText(c);
    }//GEN-LAST:event_cmdSeguridadActionPerformed

    private void cmdCambiarContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCambiarContraActionPerformed
        // TODO add your handling code here:
        clase p;
        String nueva;
        int lon;
        int sw = 1;
        do {
            try {
                nueva = JOptionPane.showInputDialog(this, "Digite nueva contraseña por favor");
                lon = nueva.length();
                p = new clase(lon, nueva);
                txtPassContra.setText(nueva);
                txtRes.setText("");
                JOptionPane.showMessageDialog(this, "Contraseña actualizada correctamente");
                sw = 1;
            } catch (NullPointerException e) {
                int res = JOptionPane.showConfirmDialog(this, "¿Seguro que quieres salir?", "Salir", JOptionPane.YES_NO_OPTION);
                if (res == 0) {
                    sw = 1;
                } else {
                    sw = 0;
                }
            }
        } while (sw == 0);


    }//GEN-LAST:event_cmdCambiarContraActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        // TODO add your handling code here:
        txtPassContra.setText("");
        txtRes.setText("");
        cmdGuardarContra.setEnabled(true);
        cmdCambiarContra.setEnabled(false);
        cmdSeguridad.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdLimpiar.setEnabled(false);
        txtPassContra.requestFocusInWindow();
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCambiarContra;
    private javax.swing.JButton cmdGuardarContra;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdSeguridad;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField txtPassContra;
    private javax.swing.JTextArea txtRes;
    // End of variables declaration//GEN-END:variables
}
